"""add place to news

Revision ID: e0ac9d9736e4
Revises: eb5657cfa408
Create Date: 2026-06-09 12:09:22.178781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ac9d9736e4'
down_revision = 'eb5657cfa408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('artwork_tags',
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_by_once', ['user_id', 'artwork_id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_like', ['user_id', 'artwork_id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_like', type_='unique')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_by_once', type_='unique')

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))

    op.drop_table('artwork_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
